# -*- coding: utf-8 -*-
"""Untitled180.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pC0ln9niNDfm_v-ThNLbagHZLHjEs04D
"""

import numpy as np
import pandas as pd

df = pd.read_csv("movies.csv")

df.head()

df['YoR'] = df['title'].str[-5:-1]

df.to_csv('movies1.csv')